# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet_stats.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12packet_stats.proto\"\xa7\x01\n\x0bPacketStats\x12\x1f\n\x04role\x18\x01 \x01(\x0e\x32\x11.PacketStats.Role\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x04\x12\r\n\x05\x63olor\x18\x03 \x01(\r\x12\x10\n\x08\x63ounter0\x18\x04 \x01(\x04\x12\x10\n\x08\x63ounter1\x18\x05 \x01(\x04\x12\x10\n\x08interval\x18\x06 \x01(\r\"\x1c\n\x04Role\x12\n\n\x06SOURCE\x10\x00\x12\x08\n\x04SINK\x10\x01\".\n\x0fPacketStatsPush\x12\x1b\n\x05stats\x18\x01 \x01(\x0b\x32\x0c.PacketStats\"7\n\x15PacketStatsPushResult\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x14PacketStatsCollector\x12\x31\n\x03get\x12\x10.PacketStatsPush\x1a\x16.PacketStatsPushResult\"\x00\x62\x06proto3')
)



_PACKETSTATS_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='PacketStats.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOURCE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=162,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_PACKETSTATS_ROLE)


_PACKETSTATS = _descriptor.Descriptor(
  name='PacketStats',
  full_name='PacketStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='PacketStats.role', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_number', full_name='PacketStats.block_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='PacketStats.color', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter0', full_name='PacketStats.counter0', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter1', full_name='PacketStats.counter1', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='PacketStats.interval', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKETSTATS_ROLE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=190,
)


_PACKETSTATSPUSH = _descriptor.Descriptor(
  name='PacketStatsPush',
  full_name='PacketStatsPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='PacketStatsPush.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=238,
)


_PACKETSTATSPUSHRESULT = _descriptor.Descriptor(
  name='PacketStatsPushResult',
  full_name='PacketStatsPushResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='PacketStatsPushResult.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='PacketStatsPushResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=295,
)

_PACKETSTATS.fields_by_name['role'].enum_type = _PACKETSTATS_ROLE
_PACKETSTATS_ROLE.containing_type = _PACKETSTATS
_PACKETSTATSPUSH.fields_by_name['stats'].message_type = _PACKETSTATS
DESCRIPTOR.message_types_by_name['PacketStats'] = _PACKETSTATS
DESCRIPTOR.message_types_by_name['PacketStatsPush'] = _PACKETSTATSPUSH
DESCRIPTOR.message_types_by_name['PacketStatsPushResult'] = _PACKETSTATSPUSHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketStats = _reflection.GeneratedProtocolMessageType('PacketStats', (_message.Message,), dict(
  DESCRIPTOR = _PACKETSTATS,
  __module__ = 'packet_stats_pb2'
  # @@protoc_insertion_point(class_scope:PacketStats)
  ))
_sym_db.RegisterMessage(PacketStats)

PacketStatsPush = _reflection.GeneratedProtocolMessageType('PacketStatsPush', (_message.Message,), dict(
  DESCRIPTOR = _PACKETSTATSPUSH,
  __module__ = 'packet_stats_pb2'
  # @@protoc_insertion_point(class_scope:PacketStatsPush)
  ))
_sym_db.RegisterMessage(PacketStatsPush)

PacketStatsPushResult = _reflection.GeneratedProtocolMessageType('PacketStatsPushResult', (_message.Message,), dict(
  DESCRIPTOR = _PACKETSTATSPUSHRESULT,
  __module__ = 'packet_stats_pb2'
  # @@protoc_insertion_point(class_scope:PacketStatsPushResult)
  ))
_sym_db.RegisterMessage(PacketStatsPushResult)



_PACKETSTATSCOLLECTOR = _descriptor.ServiceDescriptor(
  name='PacketStatsCollector',
  full_name='PacketStatsCollector',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=297,
  serialized_end=370,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='PacketStatsCollector.get',
    index=0,
    containing_service=None,
    input_type=_PACKETSTATSPUSH,
    output_type=_PACKETSTATSPUSHRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKETSTATSCOLLECTOR)

DESCRIPTOR.services_by_name['PacketStatsCollector'] = _PACKETSTATSCOLLECTOR

# @@protoc_insertion_point(module_scope)
