# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import packet_stats_pb2 as packet__stats__pb2


class PacketStatsCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get = channel.unary_unary(
        '/PacketStatsCollector/get',
        request_serializer=packet__stats__pb2.PacketStatsPush.SerializeToString,
        response_deserializer=packet__stats__pb2.PacketStatsPushResult.FromString,
        )


class PacketStatsCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PacketStatsCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=packet__stats__pb2.PacketStatsPush.FromString,
          response_serializer=packet__stats__pb2.PacketStatsPushResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PacketStatsCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
